
spring.data.mongodb.uri=${{ secrets.MONGO_URI }}
spring.data.mongodb.database=CustomerDetails

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017



